### PR TITLE
Update KeycloakWebGuardServiceProvider.php

### PR DESCRIPTION
**Pull request by Mnikoei**
Session which contains keycloak token can not be retreived in keycloakWeb middleware becuase of missing EncryptCookies and AddQueuedCookiesToResponse middlewares on routes defined in KeycloakWebGuardServiceProvider.php

### CODE REVIEW

**Comment by cdkey22** [comment]
I agree and did the same correction before seeing your suggestion (so many time lost).
Is the merge scheduled ?
Thank you

**Comment by mariovalney** [comment]
Hi @Mnikoei .
Thanks for your contribution.

I tested here and everything is ok.
I just do not want to keep a dependency from "web" group as it can be modified by user to its purposes.

May I ask you to update your PR to something like:

```
$middlewares = [
    \App\Http\Middleware\EncryptCookies::class,
    \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
    \Illuminate\Session\Middleware\StartSession::class,
];
```

And use this value at middlewares?

**Comment by mariovalney** [comment]
Hi @Mnikoei .
Thanks for your contribution.

I tested here and everything is ok.

Sorry guys for take so long to merge.

**Comment by cdkey22** [comment]
Allright , I did test your release using v1.5.0 in composer and it seems to work. 
Thank you for the job you did !

**Pull request merged**
