### PR TITLE
[wip] feat: keycloak sync command

### PR DESCRIPTION
**Pull request by gpedro**
### how works:
i used keycloak admin api to retrieve all users and sync on the local database.

### setup:
after setup environment configs, add a new column on users table
```
$table->uuid('keycloak_id');
```
and finally run `php artisan keycloak:sync`

### changelog:
```
added:
- environment config: KEYCLOAK_ADMIN_USERNAME, KEYCLOAK_ADMIN_PASSWORD
- command keycloak:sync

changes:
- cleanup unused dependencies

known issues:
- admin api returns only 100 users, need to implement GET /{realm}/users/count.
```

### CODE REVIEW

**Comment by mariovalney** [comment]
Hi! How are you?

We really appreciate contributions.
But I would ask you to open a issue so we can discuss the feature before implementing it.

As it's a WIP, no problem: we can talk about later, if you prefer.

Thanks again.

**Comment by gpedro** [comment]
@mariovalney ok, issue created. #35

**Comment by mariovalney** [comment]
HI @gpedro !

Is this feature finished?
As this have the "WIP" tag I don't checked yet.
I'm sorry I missed something.

**Comment by gpedro** [comment]
not yet.

**Comment by francoisauclair911** [comment]
Any update on this?

**Pull request closed without merging**
